# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trainer_to_scheduler.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='trainer_to_scheduler.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1atrainer_to_scheduler.proto\x1a\x0c\x63ommon.proto\"%\n\x13ReportStableRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\r\"(\n\x12ReportReadyRequest\x12\x12\n\ntrainer_id\x18\x01 \x01(\r2r\n\x12TrainerToScheduler\x12.\n\x0cReportStable\x12\x14.ReportStableRequest\x1a\x06.Empty\"\x00\x12,\n\x0bReportReady\x12\x13.ReportReadyRequest\x1a\x06.Empty\"\x00\x62\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_REPORTSTABLEREQUEST = _descriptor.Descriptor(
  name='ReportStableRequest',
  full_name='ReportStableRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='job_id', full_name='ReportStableRequest.job_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=81,
)


_REPORTREADYREQUEST = _descriptor.Descriptor(
  name='ReportReadyRequest',
  full_name='ReportReadyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='trainer_id', full_name='ReportReadyRequest.trainer_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=123,
)

DESCRIPTOR.message_types_by_name['ReportStableRequest'] = _REPORTSTABLEREQUEST
DESCRIPTOR.message_types_by_name['ReportReadyRequest'] = _REPORTREADYREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReportStableRequest = _reflection.GeneratedProtocolMessageType('ReportStableRequest', (_message.Message,), {
  'DESCRIPTOR' : _REPORTSTABLEREQUEST,
  '__module__' : 'trainer_to_scheduler_pb2'
  # @@protoc_insertion_point(class_scope:ReportStableRequest)
  })
_sym_db.RegisterMessage(ReportStableRequest)

ReportReadyRequest = _reflection.GeneratedProtocolMessageType('ReportReadyRequest', (_message.Message,), {
  'DESCRIPTOR' : _REPORTREADYREQUEST,
  '__module__' : 'trainer_to_scheduler_pb2'
  # @@protoc_insertion_point(class_scope:ReportReadyRequest)
  })
_sym_db.RegisterMessage(ReportReadyRequest)



_TRAINERTOSCHEDULER = _descriptor.ServiceDescriptor(
  name='TrainerToScheduler',
  full_name='TrainerToScheduler',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=125,
  serialized_end=239,
  methods=[
  _descriptor.MethodDescriptor(
    name='ReportStable',
    full_name='TrainerToScheduler.ReportStable',
    index=0,
    containing_service=None,
    input_type=_REPORTSTABLEREQUEST,
    output_type=common__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ReportReady',
    full_name='TrainerToScheduler.ReportReady',
    index=1,
    containing_service=None,
    input_type=_REPORTREADYREQUEST,
    output_type=common__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRAINERTOSCHEDULER)

DESCRIPTOR.services_by_name['TrainerToScheduler'] = _TRAINERTOSCHEDULER

# @@protoc_insertion_point(module_scope)
