# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: master_to_worker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='master_to_worker.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16master_to_worker.proto\x1a\x0c\x63ommon.proto\"\xed\x01\n\x07JobInfo\x12\x10\n\x08job_name\x18\x01 \x01(\t\x12\x12\n\nbatch_size\x18\x02 \x01(\r\x12\x0e\n\x06job_id\x18\x03 \x01(\r\x12\x16\n\x0enproc_per_node\x18\x04 \x01(\r\x12\x0e\n\x06nnodes\x18\x05 \x01(\r\x12\x11\n\tnode_rank\x18\x06 \x01(\r\x12\x11\n\tmaster_ip\x18\x07 \x01(\t\x12\x13\n\x0bmaster_port\x18\x08 \x01(\r\x12\x10\n\x08gpu_list\x18\t \x01(\r\x12\x12\n\niterations\x18\n \x01(\r\x12\r\n\x05ranks\x18\x0b \x03(\r\x12\x14\n\x0c\x66rom_scratch\x18\x0c \x01(\x08\"+\n\rRunJobRequest\x12\x1a\n\x08job_info\x18\x01 \x01(\x0b\x32\x08.JobInfo\".\n\x10UpdateJobRequest\x12\x1a\n\x08job_info\x18\x01 \x01(\x0b\x32\x08.JobInfo\"D\n\x10\x42roadcastRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\r\x12\x13\n\x0bglobal_rank\x18\x02 \x01(\r\x12\x0b\n\x03src\x18\x03 \x01(\r\"N\n\x0fNewGroupRequest\x12\x0f\n\x07\x66or_ddp\x18\x01 \x01(\x08\x12\x0e\n\x06job_id\x18\x02 \x01(\r\x12\r\n\x05ranks\x18\x03 \x03(\r\x12\x0b\n\x03src\x18\x04 \x01(\r\" \n\x0eKillJobRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\r2\xb7\x02\n\x0eMasterToWorker\x12\"\n\x06RunJob\x12\x0e.RunJobRequest\x1a\x06.Empty\"\x00\x12(\n\tUpdateJob\x12\x11.UpdateJobRequest\x1a\x06.Empty\"\x00\x12&\n\x08NewGroup\x12\x10.NewGroupRequest\x1a\x06.Empty\"\x00\x12$\n\x07KillJob\x12\x0f.KillJobRequest\x1a\x06.Empty\"\x00\x12#\n\x0f\x42roadcastFinish\x12\x06.Empty\x1a\x06.Empty\"\x00\x12!\n\rTrainingBegin\x12\x06.Empty\x1a\x06.Empty\"\x00\x12#\n\x0fRestartTrainers\x12\x06.Empty\x1a\x06.Empty\"\x00\x12\x1c\n\x08ShutDown\x12\x06.Empty\x1a\x06.Empty\"\x00\x62\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_JOBINFO = _descriptor.Descriptor(
  name='JobInfo',
  full_name='JobInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='job_name', full_name='JobInfo.job_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='batch_size', full_name='JobInfo.batch_size', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='job_id', full_name='JobInfo.job_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nproc_per_node', full_name='JobInfo.nproc_per_node', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nnodes', full_name='JobInfo.nnodes', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node_rank', full_name='JobInfo.node_rank', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='master_ip', full_name='JobInfo.master_ip', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='master_port', full_name='JobInfo.master_port', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gpu_list', full_name='JobInfo.gpu_list', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='iterations', full_name='JobInfo.iterations', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ranks', full_name='JobInfo.ranks', index=10,
      number=11, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='from_scratch', full_name='JobInfo.from_scratch', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=278,
)


_RUNJOBREQUEST = _descriptor.Descriptor(
  name='RunJobRequest',
  full_name='RunJobRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='job_info', full_name='RunJobRequest.job_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=280,
  serialized_end=323,
)


_UPDATEJOBREQUEST = _descriptor.Descriptor(
  name='UpdateJobRequest',
  full_name='UpdateJobRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='job_info', full_name='UpdateJobRequest.job_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=325,
  serialized_end=371,
)


_BROADCASTREQUEST = _descriptor.Descriptor(
  name='BroadcastRequest',
  full_name='BroadcastRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='job_id', full_name='BroadcastRequest.job_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='global_rank', full_name='BroadcastRequest.global_rank', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='src', full_name='BroadcastRequest.src', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=373,
  serialized_end=441,
)


_NEWGROUPREQUEST = _descriptor.Descriptor(
  name='NewGroupRequest',
  full_name='NewGroupRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='for_ddp', full_name='NewGroupRequest.for_ddp', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='job_id', full_name='NewGroupRequest.job_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ranks', full_name='NewGroupRequest.ranks', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='src', full_name='NewGroupRequest.src', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=443,
  serialized_end=521,
)


_KILLJOBREQUEST = _descriptor.Descriptor(
  name='KillJobRequest',
  full_name='KillJobRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='job_id', full_name='KillJobRequest.job_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=523,
  serialized_end=555,
)

_RUNJOBREQUEST.fields_by_name['job_info'].message_type = _JOBINFO
_UPDATEJOBREQUEST.fields_by_name['job_info'].message_type = _JOBINFO
DESCRIPTOR.message_types_by_name['JobInfo'] = _JOBINFO
DESCRIPTOR.message_types_by_name['RunJobRequest'] = _RUNJOBREQUEST
DESCRIPTOR.message_types_by_name['UpdateJobRequest'] = _UPDATEJOBREQUEST
DESCRIPTOR.message_types_by_name['BroadcastRequest'] = _BROADCASTREQUEST
DESCRIPTOR.message_types_by_name['NewGroupRequest'] = _NEWGROUPREQUEST
DESCRIPTOR.message_types_by_name['KillJobRequest'] = _KILLJOBREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JobInfo = _reflection.GeneratedProtocolMessageType('JobInfo', (_message.Message,), {
  'DESCRIPTOR' : _JOBINFO,
  '__module__' : 'master_to_worker_pb2'
  # @@protoc_insertion_point(class_scope:JobInfo)
  })
_sym_db.RegisterMessage(JobInfo)

RunJobRequest = _reflection.GeneratedProtocolMessageType('RunJobRequest', (_message.Message,), {
  'DESCRIPTOR' : _RUNJOBREQUEST,
  '__module__' : 'master_to_worker_pb2'
  # @@protoc_insertion_point(class_scope:RunJobRequest)
  })
_sym_db.RegisterMessage(RunJobRequest)

UpdateJobRequest = _reflection.GeneratedProtocolMessageType('UpdateJobRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEJOBREQUEST,
  '__module__' : 'master_to_worker_pb2'
  # @@protoc_insertion_point(class_scope:UpdateJobRequest)
  })
_sym_db.RegisterMessage(UpdateJobRequest)

BroadcastRequest = _reflection.GeneratedProtocolMessageType('BroadcastRequest', (_message.Message,), {
  'DESCRIPTOR' : _BROADCASTREQUEST,
  '__module__' : 'master_to_worker_pb2'
  # @@protoc_insertion_point(class_scope:BroadcastRequest)
  })
_sym_db.RegisterMessage(BroadcastRequest)

NewGroupRequest = _reflection.GeneratedProtocolMessageType('NewGroupRequest', (_message.Message,), {
  'DESCRIPTOR' : _NEWGROUPREQUEST,
  '__module__' : 'master_to_worker_pb2'
  # @@protoc_insertion_point(class_scope:NewGroupRequest)
  })
_sym_db.RegisterMessage(NewGroupRequest)

KillJobRequest = _reflection.GeneratedProtocolMessageType('KillJobRequest', (_message.Message,), {
  'DESCRIPTOR' : _KILLJOBREQUEST,
  '__module__' : 'master_to_worker_pb2'
  # @@protoc_insertion_point(class_scope:KillJobRequest)
  })
_sym_db.RegisterMessage(KillJobRequest)



_MASTERTOWORKER = _descriptor.ServiceDescriptor(
  name='MasterToWorker',
  full_name='MasterToWorker',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=558,
  serialized_end=869,
  methods=[
  _descriptor.MethodDescriptor(
    name='RunJob',
    full_name='MasterToWorker.RunJob',
    index=0,
    containing_service=None,
    input_type=_RUNJOBREQUEST,
    output_type=common__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateJob',
    full_name='MasterToWorker.UpdateJob',
    index=1,
    containing_service=None,
    input_type=_UPDATEJOBREQUEST,
    output_type=common__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='NewGroup',
    full_name='MasterToWorker.NewGroup',
    index=2,
    containing_service=None,
    input_type=_NEWGROUPREQUEST,
    output_type=common__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='KillJob',
    full_name='MasterToWorker.KillJob',
    index=3,
    containing_service=None,
    input_type=_KILLJOBREQUEST,
    output_type=common__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='BroadcastFinish',
    full_name='MasterToWorker.BroadcastFinish',
    index=4,
    containing_service=None,
    input_type=common__pb2._EMPTY,
    output_type=common__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TrainingBegin',
    full_name='MasterToWorker.TrainingBegin',
    index=5,
    containing_service=None,
    input_type=common__pb2._EMPTY,
    output_type=common__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RestartTrainers',
    full_name='MasterToWorker.RestartTrainers',
    index=6,
    containing_service=None,
    input_type=common__pb2._EMPTY,
    output_type=common__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ShutDown',
    full_name='MasterToWorker.ShutDown',
    index=7,
    containing_service=None,
    input_type=common__pb2._EMPTY,
    output_type=common__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MASTERTOWORKER)

DESCRIPTOR.services_by_name['MasterToWorker'] = _MASTERTOWORKER

# @@protoc_insertion_point(module_scope)
