# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scheduler_to_master.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='scheduler_to_master.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19scheduler_to_master.proto\x1a\x0c\x63ommon.proto\"\"\n\x0fScheduleRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\":\n\x10ScheduleResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t2\x8e\x01\n\x11SchedulerToMaster\x12\x31\n\x08Schedule\x12\x10.ScheduleRequest\x1a\x11.ScheduleResponse\"\x00\x12#\n\x0f\x42roadcastFinish\x12\x06.Empty\x1a\x06.Empty\"\x00\x12!\n\rTrainingBegin\x12\x06.Empty\x1a\x06.Empty\"\x00\x62\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_SCHEDULEREQUEST = _descriptor.Descriptor(
  name='ScheduleRequest',
  full_name='ScheduleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='ScheduleRequest.command', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=77,
)


_SCHEDULERESPONSE = _descriptor.Descriptor(
  name='ScheduleResponse',
  full_name='ScheduleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='ScheduleResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_message', full_name='ScheduleResponse.error_message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=137,
)

DESCRIPTOR.message_types_by_name['ScheduleRequest'] = _SCHEDULEREQUEST
DESCRIPTOR.message_types_by_name['ScheduleResponse'] = _SCHEDULERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ScheduleRequest = _reflection.GeneratedProtocolMessageType('ScheduleRequest', (_message.Message,), {
  'DESCRIPTOR' : _SCHEDULEREQUEST,
  '__module__' : 'scheduler_to_master_pb2'
  # @@protoc_insertion_point(class_scope:ScheduleRequest)
  })
_sym_db.RegisterMessage(ScheduleRequest)

ScheduleResponse = _reflection.GeneratedProtocolMessageType('ScheduleResponse', (_message.Message,), {
  'DESCRIPTOR' : _SCHEDULERESPONSE,
  '__module__' : 'scheduler_to_master_pb2'
  # @@protoc_insertion_point(class_scope:ScheduleResponse)
  })
_sym_db.RegisterMessage(ScheduleResponse)



_SCHEDULERTOMASTER = _descriptor.ServiceDescriptor(
  name='SchedulerToMaster',
  full_name='SchedulerToMaster',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=140,
  serialized_end=282,
  methods=[
  _descriptor.MethodDescriptor(
    name='Schedule',
    full_name='SchedulerToMaster.Schedule',
    index=0,
    containing_service=None,
    input_type=_SCHEDULEREQUEST,
    output_type=_SCHEDULERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='BroadcastFinish',
    full_name='SchedulerToMaster.BroadcastFinish',
    index=1,
    containing_service=None,
    input_type=common__pb2._EMPTY,
    output_type=common__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TrainingBegin',
    full_name='SchedulerToMaster.TrainingBegin',
    index=2,
    containing_service=None,
    input_type=common__pb2._EMPTY,
    output_type=common__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SCHEDULERTOMASTER)

DESCRIPTOR.services_by_name['SchedulerToMaster'] = _SCHEDULERTOMASTER

# @@protoc_insertion_point(module_scope)
