# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worker_to_trainer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='worker_to_trainer.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17worker_to_trainer.proto\x1a\x0c\x63ommon.proto\"R\n\x13InitNewGroupRequest\x12\x0f\n\x07\x66or_ddp\x18\x01 \x01(\x08\x12\x0e\n\x06job_id\x18\x02 \x01(\r\x12\r\n\x05ranks\x18\x03 \x03(\r\x12\x0b\n\x03src\x18\x04 \x01(\r\"\xd4\x01\n\x12InitStandbyRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\r\x12\x10\n\x08job_name\x18\x02 \x01(\t\x12\x13\n\x0bmaster_addr\x18\x03 \x01(\t\x12\x13\n\x0bmaster_port\x18\x04 \x01(\r\x12\x0c\n\x04rank\x18\x05 \x01(\r\x12\x12\n\nlocal_rank\x18\x06 \x01(\r\x12\x12\n\nworld_size\x18\x07 \x01(\r\x12\x12\n\nbatch_size\x18\x08 \x01(\r\x12\x12\n\niterations\x18\t \x01(\r\x12\x14\n\x0c\x66rom_scratch\x18\n \x01(\x08\"H\n\x14SendOrReceiveRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\r\x12\x13\n\x0bglobal_rank\x18\x02 \x01(\r\x12\x0b\n\x03src\x18\x03 \x01(\x08\"#\n\x11KillActiveRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\r\"\x14\n\x12KillTrainerRequest2\xaf\x02\n\x0fWorkerToTrainer\x12*\n\x08NewGroup\x12\x14.InitNewGroupRequest\x1a\x06.Empty\"\x00\x12#\n\x0f\x42roadcastFinish\x12\x06.Empty\x1a\x06.Empty\"\x00\x12!\n\rTrainingBegin\x12\x06.Empty\x1a\x06.Empty\"\x00\x12,\n\x0bInitStandby\x12\x13.InitStandbyRequest\x1a\x06.Empty\"\x00\x12*\n\nKillActive\x12\x12.KillActiveRequest\x1a\x06.Empty\"\x00\x12,\n\x0bKillTrainer\x12\x13.KillTrainerRequest\x1a\x06.Empty\"\x00\x12 \n\x0cProbeTrainer\x12\x06.Empty\x1a\x06.Empty\"\x00\x62\x06proto3'
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_INITNEWGROUPREQUEST = _descriptor.Descriptor(
  name='InitNewGroupRequest',
  full_name='InitNewGroupRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='for_ddp', full_name='InitNewGroupRequest.for_ddp', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='job_id', full_name='InitNewGroupRequest.job_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ranks', full_name='InitNewGroupRequest.ranks', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='src', full_name='InitNewGroupRequest.src', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=123,
)


_INITSTANDBYREQUEST = _descriptor.Descriptor(
  name='InitStandbyRequest',
  full_name='InitStandbyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='job_id', full_name='InitStandbyRequest.job_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='job_name', full_name='InitStandbyRequest.job_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='master_addr', full_name='InitStandbyRequest.master_addr', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='master_port', full_name='InitStandbyRequest.master_port', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rank', full_name='InitStandbyRequest.rank', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='local_rank', full_name='InitStandbyRequest.local_rank', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='world_size', full_name='InitStandbyRequest.world_size', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='batch_size', full_name='InitStandbyRequest.batch_size', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='iterations', full_name='InitStandbyRequest.iterations', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='from_scratch', full_name='InitStandbyRequest.from_scratch', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=338,
)


_SENDORRECEIVEREQUEST = _descriptor.Descriptor(
  name='SendOrReceiveRequest',
  full_name='SendOrReceiveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='job_id', full_name='SendOrReceiveRequest.job_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='global_rank', full_name='SendOrReceiveRequest.global_rank', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='src', full_name='SendOrReceiveRequest.src', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=340,
  serialized_end=412,
)


_KILLACTIVEREQUEST = _descriptor.Descriptor(
  name='KillActiveRequest',
  full_name='KillActiveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='job_id', full_name='KillActiveRequest.job_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=414,
  serialized_end=449,
)


_KILLTRAINERREQUEST = _descriptor.Descriptor(
  name='KillTrainerRequest',
  full_name='KillTrainerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=451,
  serialized_end=471,
)

DESCRIPTOR.message_types_by_name['InitNewGroupRequest'] = _INITNEWGROUPREQUEST
DESCRIPTOR.message_types_by_name['InitStandbyRequest'] = _INITSTANDBYREQUEST
DESCRIPTOR.message_types_by_name['SendOrReceiveRequest'] = _SENDORRECEIVEREQUEST
DESCRIPTOR.message_types_by_name['KillActiveRequest'] = _KILLACTIVEREQUEST
DESCRIPTOR.message_types_by_name['KillTrainerRequest'] = _KILLTRAINERREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InitNewGroupRequest = _reflection.GeneratedProtocolMessageType('InitNewGroupRequest', (_message.Message,), {
  'DESCRIPTOR' : _INITNEWGROUPREQUEST,
  '__module__' : 'worker_to_trainer_pb2'
  # @@protoc_insertion_point(class_scope:InitNewGroupRequest)
  })
_sym_db.RegisterMessage(InitNewGroupRequest)

InitStandbyRequest = _reflection.GeneratedProtocolMessageType('InitStandbyRequest', (_message.Message,), {
  'DESCRIPTOR' : _INITSTANDBYREQUEST,
  '__module__' : 'worker_to_trainer_pb2'
  # @@protoc_insertion_point(class_scope:InitStandbyRequest)
  })
_sym_db.RegisterMessage(InitStandbyRequest)

SendOrReceiveRequest = _reflection.GeneratedProtocolMessageType('SendOrReceiveRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENDORRECEIVEREQUEST,
  '__module__' : 'worker_to_trainer_pb2'
  # @@protoc_insertion_point(class_scope:SendOrReceiveRequest)
  })
_sym_db.RegisterMessage(SendOrReceiveRequest)

KillActiveRequest = _reflection.GeneratedProtocolMessageType('KillActiveRequest', (_message.Message,), {
  'DESCRIPTOR' : _KILLACTIVEREQUEST,
  '__module__' : 'worker_to_trainer_pb2'
  # @@protoc_insertion_point(class_scope:KillActiveRequest)
  })
_sym_db.RegisterMessage(KillActiveRequest)

KillTrainerRequest = _reflection.GeneratedProtocolMessageType('KillTrainerRequest', (_message.Message,), {
  'DESCRIPTOR' : _KILLTRAINERREQUEST,
  '__module__' : 'worker_to_trainer_pb2'
  # @@protoc_insertion_point(class_scope:KillTrainerRequest)
  })
_sym_db.RegisterMessage(KillTrainerRequest)



_WORKERTOTRAINER = _descriptor.ServiceDescriptor(
  name='WorkerToTrainer',
  full_name='WorkerToTrainer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=474,
  serialized_end=777,
  methods=[
  _descriptor.MethodDescriptor(
    name='NewGroup',
    full_name='WorkerToTrainer.NewGroup',
    index=0,
    containing_service=None,
    input_type=_INITNEWGROUPREQUEST,
    output_type=common__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='BroadcastFinish',
    full_name='WorkerToTrainer.BroadcastFinish',
    index=1,
    containing_service=None,
    input_type=common__pb2._EMPTY,
    output_type=common__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TrainingBegin',
    full_name='WorkerToTrainer.TrainingBegin',
    index=2,
    containing_service=None,
    input_type=common__pb2._EMPTY,
    output_type=common__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='InitStandby',
    full_name='WorkerToTrainer.InitStandby',
    index=3,
    containing_service=None,
    input_type=_INITSTANDBYREQUEST,
    output_type=common__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='KillActive',
    full_name='WorkerToTrainer.KillActive',
    index=4,
    containing_service=None,
    input_type=_KILLACTIVEREQUEST,
    output_type=common__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='KillTrainer',
    full_name='WorkerToTrainer.KillTrainer',
    index=5,
    containing_service=None,
    input_type=_KILLTRAINERREQUEST,
    output_type=common__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ProbeTrainer',
    full_name='WorkerToTrainer.ProbeTrainer',
    index=6,
    containing_service=None,
    input_type=common__pb2._EMPTY,
    output_type=common__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_WORKERTOTRAINER)

DESCRIPTOR.services_by_name['WorkerToTrainer'] = _WORKERTOTRAINER

# @@protoc_insertion_point(module_scope)
